// Domyślny plan — źródło: "Plan Żywieniowy i Treningowy - Redukcja 2400 kcal V2"
// Zmiany robione w aplikacji zapisują się w localStorage i nadpisują ten plik.
//
// recipe.steps — kroki przygotowania, recipe.tip — jak zbić kalorie bez utraty smaku.
// Zasada przewodnia: tłuszcz dodany to najdroższa kaloria w daniu (oliwa/masło ~90 kcal
// na 10 g). Patelnia nieprzywierająca, spray zamiast lania z butelki i air fryer zamiast
// głębokiego tłuszczu zbijają porcję o 100–300 kcal przy tych samych składnikach.

const DEFAULT_PLAN = {
  version: 2,
  title: "Redukcja 2400 kcal",
  target: 2400,
  days: [
    {
      id: "mon", name: "Poniedziałek", short: "Pn",
      activity: "Siłownia (FBW)", activityIcon: "🏋️",
      meals: [
        { id: "mon-1", slot: "Śniadanie", name: "Jajecznica z warzywami", kcal: 600,
          items: "4 jajka L, 3 kromki chleba żytniego (90g), 10g masła, 1 duży pomidor",
          recipe: { steps: [
            "Pomidora pokrój w kostkę i odsącz z nadmiaru soku — jajecznica nie zrobi się wodnista.",
            "Rozgrzej patelnię nieprzywierającą na średnim ogniu, rozprowadź masło po całej powierzchni.",
            "Wrzuć pomidora na 2 minuty, aż odparuje.",
            "Roztrzep jajka widelcem, wlej na patelnię i ścinaj na małym ogniu, ciągle mieszając.",
            "Zdejmij, gdy masa jest jeszcze lekko wilgotna — dojdzie na talerzu. Sól i pieprz na koniec.",
          ], tip: "Na dobrej patelni nieprzywierającej wystarczy 5 g masła zamiast 10 g (–45 kcal). Smak nadrobisz szczypiorkiem, papryką wędzoną i świeżo mielonym pieprzem." } },
        { id: "mon-2", slot: "Przekąska", name: "Skyr orzechowo-owocowy", kcal: 300,
          items: "Skyr waniliowy (150g), 100g borówek, 20g masła orzechowego",
          recipe: { steps: [
            "Masło orzechowe rozmieszaj najpierw z 2 łyżkami skyru — łatwiej się połączy niż wrzucone w całość.",
            "Dodaj resztę skyru i wymieszaj.",
            "Borówki wsyp na wierzch, nie mieszaj — zostaną jędrne.",
          ], tip: "Masło orzechowe odmierzaj płaską łyżką i najlepiej na wadze: 20 g to ~120 kcal, a „kopiasta łyżka” to spokojnie 35 g, czyli ~90 kcal więcej niż zakłada plan." } },
        { id: "mon-3", slot: "Obiad", name: "Kurczak z Air Fryer", kcal: 800, note: "Gotuj x2 — porcja na wtorek",
          items: "250g piersi z kurczaka, 400g ziemniaków, 15g oliwy, 150g mizerii",
          recipe: { steps: [
            "Ziemniaki pokrój w ćwiartki, zalej wrzątkiem na 5 minut, odcedź i dobrze osusz — para na powierzchni to wróg chrupkości.",
            "Wymieszaj je z 10 g oliwy, papryką słodką, czosnkiem granulowanym i solą.",
            "Air fryer 190°C, 20–25 minut, potrząśnij koszykiem w połowie.",
            "Pierś natrzyj resztą oliwy i przyprawami, dołóż na ostatnie 12–14 minut (w środku 74°C).",
            "Mizeria: ogórek na cienkie plastry, posól, odstaw 10 minut, odciśnij wodę i wymieszaj ze skyrem, koperkiem i pieprzem.",
          ], tip: "Dwie oszczędności: mizeria na skyrze zamiast na śmietanie 18% to ~60 kcal mniej, a oliwa rozprowadzona sprayem lub pędzelkiem zamiast lana z butelki pozwala zejść z 15 g do 8 g (–60 kcal). Air fryer wymaga ~70–80% mniej tłuszczu niż smażenie." } },
        { id: "mon-4", slot: "Kolacja", name: "Tortilla z wędliną i serem", kcal: 750,
          items: "2 tortille pełnoziarniste, 100g szynki drobiowej, 60g mozzarelli light, szpinak, sos czosnkowy (skyr)",
          recipe: { steps: [
            "Sos: skyr naturalny + przeciśnięty ząbek czosnku + sól, pieprz, sok z cytryny. Odstaw na 10 minut, żeby czosnek się rozszedł.",
            "Tortillę posmaruj sosem, ułóż szpinak, szynkę i startą mozzarellę.",
            "Zawiń boki do środka i zroluj ciasno.",
            "Podgrzej na suchej patelni grillowej po 2 minuty z każdej strony — bez tłuszczu, ser sam sklei rolkę.",
          ], tip: "Suchą patelnią zamiast smażenia na oleju oszczędzasz ~90 kcal. Sos czosnkowy na skyrze zamiast majonezowego to różnica rzędu 150–200 kcal na porcję." } },
      ],
    },
    {
      id: "tue", name: "Wtorek", short: "Wt",
      activity: "Bieganie (2–3 km)", activityIcon: "🏃",
      meals: [
        { id: "tue-1", slot: "Śniadanie", name: "Sadzone jajka z szynką", kcal: 600,
          items: "3 jajka L, 50g szynki z piersi indyka, 3 kromki chleba żytniego, 10g masła, ogórek",
          recipe: { steps: [
            "Szynkę podsmaż 1 minutę na suchej, dobrze rozgrzanej patelni — puści własny tłuszcz.",
            "Odsuń szynkę na bok, dodaj masło i wbij jajka.",
            "Przykryj patelnię pokrywką na 2–3 minuty: para zetnie białko na wierzchu, a żółtko zostanie płynne bez przewracania.",
            "Podawaj z chlebem i ogórkiem w plastrach.",
          ], tip: "Sztuczka z pokrywką pozwala zejść z 10 g masła do 5 g, bo nie musisz polewać jajek tłuszczem z patelni (–45 kcal). Jajka gotowane w koszulce to zero dodanego tłuszczu (–75 kcal)." } },
        { id: "tue-2", slot: "Przekąska", name: "Bananowy budyń proteinowy", kcal: 300,
          items: "Pudding proteinowy (200g), 1 średni banan",
          recipe: { steps: [
            "Banana pokrój w plastry.",
            "Wymieszaj z puddingiem albo ułóż warstwami w szklance.",
            "Opcjonalnie oprósz cynamonem — podbija słodycz bez kalorii.",
          ], tip: "Banan zjedzony lekko niedojrzały (jeszcze zielonkawy przy ogonku) ma więcej skrobi opornej i mocniej syci przy tej samej kaloryczności." } },
        { id: "tue-3", slot: "Obiad", name: "Odgrzany kurczak", kcal: 800, note: "Z poniedziałku",
          items: "Wczorajsza porcja kurczaka z ziemniakami z Air Fryer",
          recipe: { steps: [
            "Ziemniaki wrzuć do air fryera na 180°C na 5–6 minut — odzyskają chrupkość, mikrofala je rozmiękczy.",
            "Pierś podgrzewaj osobno i krócej: 2–3 minuty, albo w mikrofali pod przykryciem z łyżką wody.",
            "Świeżą mizerię zrób na miejscu — wczorajsza puści wodę.",
          ], tip: "Nie dodawaj oliwy przy odgrzewaniu, tłuszcz z wczoraj nadal tam jest. Ziemniaki schłodzone przez noc mają więcej skrobi opornej, więc dają łagodniejszy skok cukru niż świeżo ugotowane." } },
        { id: "tue-4", slot: "Kolacja", name: "Domowy burger z chudej wołowiny", kcal: 750,
          items: "1 bułka pełnoziarnista, 150g chudej mielonej wołowiny, plaster cheddara light, sałata, 150g ziemniaków z Air Fryer",
          recipe: { steps: [
            "Mięso wymieszaj tylko z solą i pieprzem — bez bułki tartej i bez jajka. Uformuj kotlet szerszy niż bułka, skurczy się.",
            "Zrób kciukiem wgłębienie na środku, żeby nie spuchł w kopułę.",
            "Smaż na mocno rozgrzanej suchej patelni grillowej po 3 minuty z każdej strony — chuda wołowina i tak puści tyle tłuszczu, ile trzeba.",
            "Plaster sera połóż na ostatnią minutę i przykryj, żeby się rozpuścił.",
            "Frytki z air fryera 190°C, 18 minut. Bułkę przypiecz na sucho.",
          ], tip: "Sucha patelnia zamiast oleju to ~90 kcal mniej. Zamiast ketchupu i majonezu daj musztardę i skyr z przyprawami — zbijasz kolejne ~120 kcal." } },
      ],
    },
    {
      id: "wed", name: "Środa", short: "Śr",
      activity: "Pływanie (300–400 m)", activityIcon: "🏊",
      meals: [
        { id: "wed-1", slot: "Śniadanie", name: "Jajecznica z łososiem", kcal: 600,
          items: "3 jajka, 50g wędzonego łososia, 2 kromki chleba żytniego, 10g masła, rzodkiewka",
          recipe: { steps: [
            "Łososia pokrój w paski i odłóż — nie smaż go, wystarczy ciepło jajek.",
            "Jajka roztrzep, ścinaj na maśle na małym ogniu, mieszając co kilka sekund.",
            "Gdy masa jest w 3/4 ścięta, zdejmij z ognia i wmieszaj łososia.",
            "Dopraw pieprzem i koperkiem. Soli dodaj minimalnie — łosoś jest już słony.",
          ], tip: "Wędzony łosoś ma sporo tłuszczu, więc tu naprawdę wystarczy 5 g masła (–45 kcal). Rzodkiewka i szczypiorek dodają chrupkości i objętości za grosze kaloryczne." } },
        { id: "wed-2", slot: "Przekąska", name: "Chrupiący serek wiejski", kcal: 300,
          items: "Serek wiejski lekki (200g), 1 małe jabłko, 15g orzechów włoskich",
          recipe: { steps: [
            "Jabłko pokrój w kostkę ze skórką — to w niej jest błonnik.",
            "Wymieszaj z serkiem.",
            "Orzechy porozgniataj palcami i posyp na wierzch tuż przed jedzeniem, żeby zostały chrupiące.",
          ], tip: "15 g orzechów to ~100 kcal, czyli jedna trzecia tej przekąski — waż je, nie syp na garść. Szczypta cynamonu i kilka kropel soku z cytryny podkręcają smak bez kalorii." } },
        { id: "wed-3", slot: "Obiad", name: "Makaron z indykiem", kcal: 800, note: "Gotuj x2 — porcja na czwartek",
          items: "100g makaronu pełnoziarnistego, 150g mielonego indyka, krojone pomidory, 10g oliwy, 30g mozzarelli light",
          recipe: { steps: [
            "Indyka podsmaż na suchej, mocno rozgrzanej patelni, rozbijając łopatką na drobne kawałki, aż się zarumieni.",
            "Dodaj oliwę, czosnek i zioła dopiero teraz — na koniec smażenia mięsa, nie na początku.",
            "Wlej pomidory, gotuj bez przykrycia 12–15 minut, aż sos zgęstnieje.",
            "Makaron ugotuj al dente, odlej pół szklanki wody z gotowania.",
            "Połącz makaron z sosem na patelni, podlej wodą z makaronu — skrobia zwiąże sos bez śmietany. Mozzarella na wierzch.",
          ], tip: "Woda z gotowania makaronu zastępuje śmietanę w wiązaniu sosu — to ~150 kcal mniej. Mięso zarumienione na sucho przed dodaniem tłuszczu ma ten sam smak przy 10 g oliwy zamiast 20 g." } },
        { id: "wed-4", slot: "Kolacja", name: "Fit Pinsa z burratą", kcal: 750,
          items: "Pół spodu do pinsy, pół kulki burraty (100g), 50g passaty pomidorowej, rukola, pomidorki cherry",
          recipe: { steps: [
            "Piekarnik rozgrzej maksymalnie (230–250°C) razem z blachą w środku.",
            "Spód posmaruj passatą doprawioną solą, oregano i odrobiną czosnku.",
            "Piecz 7–9 minut na gorącej blasze, aż brzegi się zarumienią.",
            "Burratę porwij rękami i połóż na gorącą pinsę dopiero po wyjęciu z piekarnika — pieczona się rozpuści i wytopi.",
            "Na koniec rukola i przekrojone pomidorki.",
          ], tip: "Burrata na surowo daje mocniejszy efekt smakowy niż zapieczona, więc wystarczy jej mniej. Nie polewaj gotowej pinsy oliwą — to najłatwiejsze +90 kcal w całym dniu." } },
      ],
    },
    {
      id: "thu", name: "Czwartek", short: "Cz",
      activity: "Regeneracja: spacer", activityIcon: "🚶",
      meals: [
        { id: "thu-1", slot: "Śniadanie", name: "Jajka gotowane na miękko", kcal: 600,
          items: "4 jajka, 3 kromki chleba żytniego, 10g masła, szczypiorek",
          recipe: { steps: [
            "Jajka wyjmij wcześniej z lodówki albo zalej ciepłą wodą — zimne pękają.",
            "Wkładaj do już wrzącej wody i gotuj dokładnie 6,5 minuty na płynne żółtko (7,5 min na ścięte).",
            "Przełóż od razu do zimnej wody na minutę — obieranie idzie wtedy bez walki.",
            "Chleb przypiecz w tosterze, posyp szczypiorkiem i pieprzem.",
          ], tip: "To jedyne śniadanie w planie z zerowym tłuszczem dodanym w gotowaniu. Jeśli odpuścisz masło do chleba i zastąpisz je twarożkiem, schodzisz o kolejne ~50 kcal." } },
        { id: "thu-2", slot: "Przekąska", name: "Baton i owoc", kcal: 300,
          items: "Baton proteinowy, 1 duża brzoskwinia lub nektarynka",
          recipe: { steps: [
            "Bez przygotowania — to przekąska na wyjście z domu.",
            "Owoc zjedz pierwszy: błonnik i woda zapełnią żołądek, zanim sięgniesz po baton.",
          ], tip: "Przy wyborze batona patrz na kaloryczność, nie na napis „protein”. Różnica między batonami to często 150 kcal przy tej samej ilości białka — celuj w 200 kcal i minimum 15 g białka." } },
        { id: "thu-3", slot: "Obiad", name: "Odgrzany makaron", kcal: 800, note: "Ze środy",
          items: "Wczorajsza porcja makaronu z indykiem",
          recipe: { steps: [
            "Odgrzewaj na patelni, nie w mikrofali — dodaj 2–3 łyżki wody i przykryj.",
            "Mieszaj co minutę, aż sos znów zrobi się kremowy.",
            "Świeża bazylia albo szczypta chili na koniec ożywia wczorajszy sos.",
          ], tip: "Nie dodawaj oliwy „żeby się nie kleiło” — wystarczy woda. To odruch, który potrafi dołożyć 90–180 kcal do dania, które już jest policzone." } },
        { id: "thu-4", slot: "Kolacja", name: "Twarożek z łososiem", kcal: 750,
          items: "4 kromki chleba żytniego, 50g serka kanapkowego light, 100g wędzonego łososia, koper, ogórek",
          recipe: { steps: [
            "Serek wymieszaj z posiekanym koprem, pieprzem i sokiem z cytryny.",
            "Rozsmaruj na kromkach.",
            "Ułóż plastry łososia i cienko krojony ogórek.",
            "Nie dosalaj — łosoś i serek mają już sporo soli.",
          ], tip: "Zero gotowania, więc jedyna dźwignia to serek: light zamiast zwykłego to ~60 kcal mniej przy 50 g. Cytryna i koper dają wrażenie „tłustszej” kanapki, niż jest w rzeczywistości." } },
      ],
    },
    {
      id: "fri", name: "Piątek", short: "Pt",
      activity: "Siłownia (FBW)", activityIcon: "🏋️",
      meals: [
        { id: "fri-1", slot: "Śniadanie", name: "Jajka sadzone i warzywa", kcal: 600,
          items: "3 jajka L, 50g szynki z patelni, 3 kromki chleba, 10g masła, papryka",
          recipe: { steps: [
            "Paprykę pokrój w paski i podsmaż na suchej patelni 3–4 minuty, aż lekko się przypiecze.",
            "Dorzuć szynkę na minutę.",
            "Dodaj masło, wbij jajka, przykryj pokrywką na 2–3 minuty.",
            "Zsuń wszystko na talerz, dopraw papryką wędzoną i pieprzem.",
          ], tip: "Warzywa smażone na sucho przed dodaniem tłuszczu karmelizują się i są słodsze — potem wystarczy połowa masła (–45 kcal). Papryka wędzona w proszku daje smak „smażonego” bez tłuszczu." } },
        { id: "fri-2", slot: "Przekąska", name: "Skyr z gorzką czekoladą", kcal: 300,
          items: "Skyr naturalny (150g), 15g gorzkiej czekolady, garść malin",
          recipe: { steps: [
            "Czekoladę zetrzyj na tarce zamiast łamać na kostki.",
            "Wymieszaj skyr z malinami, rozgniatając część widelcem — zabarwią i dosłodzą całość.",
            "Startą czekoladę posyp na wierzch.",
          ], tip: "Starta czekolada rozkłada się po całej powierzchni, więc 15 g smakuje jak dużo więcej. Im wyższy procent kakao, tym mniej cukru — 85% zamiast 50% to ~15 kcal mniej i mocniejszy smak." } },
        { id: "fri-3", slot: "Obiad", name: "Łosoś z ryżem i fasolką", kcal: 800,
          items: "150g świeżego łososia z Air Fryer, 100g ryżu basmati, 200g fasolki szparagowej, 10g oliwy",
          recipe: { steps: [
            "Łososia osusz papierowym ręcznikiem, posól, popieprz, skrop odrobiną soku z cytryny.",
            "Air fryer 200°C, 8–10 minut skórą do góry — skóra zrobi się chrupiąca, a tłuszcz z ryby wystarczy za natłuszczenie.",
            "Ryż gotuj w proporcji 1:1,5 pod przykryciem 12 minut, potem 5 minut bez zaglądania.",
            "Fasolkę wrzuć na wrzątek na 4–5 minuty i od razu przełóż do zimnej wody — zostanie zielona i jędrna.",
            "Oliwę wymieszaj z czosnkiem i polej fasolkę już na talerzu.",
          ], tip: "Łosoś ma dość własnego tłuszczu, żeby upiec się bez kropli oliwy — całe 10 g z przepisu przenieś na fasolkę, gdzie faktycznie coś zmienia. Oliwa polana na zimno na końcu jest wyraźniej czuć niż ta wypalona na patelni, więc starcza jej mniej." } },
        { id: "fri-4", slot: "Kolacja", name: "Tortilla z kurczakiem", kcal: 750,
          items: "2 tortille pełnoziarniste, 100g piersi kurczaka, 60g żółtego sera light, warzywa, sos jogurtowy",
          recipe: { steps: [
            "Pierś pokrój w paski, wymieszaj z papryką, kuminem i solą.",
            "Smaż na suchej, mocno rozgrzanej patelni 4–5 minut — kurczak puści sok i sam się w nim zeszkli.",
            "Sos: jogurt naturalny lub skyr + czosnek + zioła + sok z cytryny.",
            "Tortillę wypełnij warzywami, kurczakiem i serem, zroluj.",
            "Dociśnij na patelni grillowej po 2 minuty z każdej strony.",
          ], tip: "Przyprawy na sucho zamiast marynaty w oleju to ~90 kcal mniej przy identycznym smaku. Ser dawaj do środka, nie na wierzch — rozpuszczony między składnikami czuć go mocniej, więc 60 g w zupełności starcza." } },
      ],
    },
    {
      id: "sat", name: "Sobota", short: "So",
      activity: "Siatkówka plażowa", activityIcon: "🏐",
      meals: [
        { id: "sat-1", slot: "Śniadanie", name: "Wytrawna jajecznica", kcal: 600,
          items: "4 jajka, 3 kromki chleba, 10g masła, pomidor",
          recipe: { steps: [
            "Roztrzep jajka z solą i odstaw na 5 minut — sól rozluźnia białko, jajecznica wychodzi kremowsza.",
            "Rozgrzej patelnię na małym ogniu, rozprowadź masło.",
            "Wlej jajka i mieszaj powoli szpatułką, zgarniając ścięte partie do środka.",
            "Zdejmij przed pełnym ścięciem. Pomidor podaj na surowo obok.",
          ], tip: "Wolne ścinanie na małym ogniu daje kremową konsystencję bez dodawania mleka czy śmietany — to ~50 kcal mniej niż typowa „jajecznica na śmietanie”." } },
        { id: "sat-2", slot: "Przekąska", name: "Bananowy budyń proteinowy", kcal: 300,
          items: "Pudding proteinowy, 1 średni banan",
          recipe: { steps: [
            "Banana pokrój w plastry, wymieszaj z puddingiem.",
            "Przed siatkówką zjedz 45–60 minut wcześniej — banan da szybką energię bez ciężkości.",
          ], tip: "To najlepiej ustawiona przekąska w tygodniu pod trening: szybkie węglowodany z banana plus białko z puddingu. Nie zamieniaj jej tego dnia na coś tłustego, bo tłuszcz spowolni trawienie." } },
        { id: "sat-3", slot: "Obiad", name: "Polędwiczka wieprzowa", kcal: 800, note: "Gotuj x2 — porcja na niedzielę",
          items: "200g polędwiczki z Air Fryer, 400g ziemniaków, 15g oliwy, mix sałat z vinegretem",
          recipe: { steps: [
            "Polędwiczkę oczyść z błony, natrzyj solą, pieprzem, czosnkiem i tymiankiem. Odstaw 20 minut w temperaturze pokojowej.",
            "Air fryer 200°C, 18–22 minuty, obróć w połowie. W środku 63°C — wtedy zostaje różowa i soczysta.",
            "Po wyjęciu odczekaj 5 minut przed krojeniem, inaczej wypłynie z niej sok.",
            "Ziemniaki: sparz wrzątkiem 5 minut, osusz, wymieszaj z 8 g oliwy i przyprawami, air fryer 190°C przez 22 minuty.",
            "Vinegret: 5 g oliwy, ocet balsamiczny, musztarda, łyżka wody — wstrząśnij w słoiku.",
          ], tip: "Polędwiczka to jedno z najchudszych mięs wieprzowych, więc nie wymaga tłuszczu do pieczenia. Vinegret rozcieńczony wodą i musztardą trzyma się liści równie dobrze przy połowie oliwy (–45 kcal)." } },
        { id: "sat-4", slot: "Kolacja", name: "Fit Pinsa z mozzarellą i szynką", kcal: 750,
          items: "Pół spodu do pinsy, 50g mozzarelli light, 30g szynki dojrzewającej, rukola, pomidorki",
          recipe: { steps: [
            "Piekarnik i blacha rozgrzane do maksimum (230–250°C).",
            "Mozzarellę osusz z zalewy i porwij na kawałki — mokra zaleje spód wodą.",
            "Piecz sam spód z serem 7–9 minut.",
            "Szynkę dojrzewającą ułóż po wyjęciu z piekarnika — pieczona traci aromat i robi się słona.",
            "Na wierzch rukola i pomidorki.",
          ], tip: "Szynka dojrzewająca jest intensywna, więc 30 g wystarcza za dwa razy tyle zwykłej. Mozzarella light zamiast klasycznej to ~70 kcal mniej przy 50 g." } },
      ],
    },
    {
      id: "sun", name: "Niedziela", short: "Nd",
      activity: "Dzień odpoczynku", activityIcon: "😴",
      meals: [
        { id: "sun-1", slot: "Śniadanie", name: "Gotowane jajka z pieczywem", kcal: 600,
          items: "4 jajka, 3 kromki chleba, 10g masła, ogórek",
          recipe: { steps: [
            "Wkładaj jajka do wrzącej wody: 6,5 minuty na płynne żółtko, 9 minut na w pełni ścięte.",
            "Przerzuć do zimnej wody na minutę.",
            "Chleb przypiecz, cienko posmaruj masłem, ułóż jajka i ogórek.",
            "Sól, pieprz, ewentualnie szczypta papryki wędzonej.",
          ], tip: "Gotowanie nie dodaje ani jednej kalorii — cały dodany tłuszcz to masło do chleba. Rozsmaruj je na ciepłym toście, wtedy 5 g pokryje wszystkie trzy kromki (–37 kcal)." } },
        { id: "sun-2", slot: "Przekąska", name: "Owocowa sałatka", kcal: 300,
          items: "1 jabłko, 1 brzoskwinia, 150g chudego twarogu, łyżeczka miodu",
          recipe: { steps: [
            "Twaróg rozgnieć widelcem z 2 łyżkami wody albo mleka — zrobi się kremowy bez dodawania śmietany.",
            "Owoce pokrój w kostkę, jabłko ze skórką.",
            "Wymieszaj, polej miodem i oprósz cynamonem.",
          ], tip: "Miód odmierzaj płaską łyżeczką: 7 g to ~22 kcal, ale „solidna łyżka” to 20 g i ~62 kcal. Cynamon pozwala zejść z miodem o połowę, bo sam wzmacnia odczucie słodyczy." } },
        { id: "sun-3", slot: "Obiad", name: "Odgrzana polędwiczka", kcal: 800, note: "Z soboty",
          items: "Wczorajsza porcja polędwiczki z ziemniakami",
          recipe: { steps: [
            "Polędwiczkę odgrzewaj delikatnie: plastry na patelni z łyżką wody, pod przykryciem, 2 minuty. Za długo i zrobi się sucha.",
            "Ziemniaki do air fryera na 180°C na 5 minut.",
            "Świeża sałata i vinegret zrobione na bieżąco.",
          ], tip: "Chude mięso wysycha przy odgrzewaniu, a odruch podlania go tłuszczem to +90 kcal. Woda pod przykrywką robi dokładnie to samo za darmo." } },
        { id: "sun-4", slot: "Kolacja", name: "Domowy burger z wołowiną", kcal: 750,
          items: "1 bułka pełnoziarnista, 150g mielonej chudej wołowiny, plaster sera, warzywa, 150g ziemniaków",
          recipe: { steps: [
            "Mięso przypraw solą i pieprzem dopiero tuż przed formowaniem — sól wcześniej wyciąga wodę.",
            "Uformuj kotlet z wgłębieniem na środku.",
            "Sucha patelnia grillowa, mocny ogień, 3 minuty na stronę, przewróć tylko raz.",
            "Ser na ostatnią minutę pod przykryciem.",
            "Ziemniaki z air fryera 190°C, 18 minut. Bułkę przypiecz na sucho przekrojoną stroną.",
          ], tip: "Przypieczona bułka nie nasiąka sosem, więc burger nie rozpada się i nie potrzebuje dodatkowego smarowania tłuszczem. Sosy buduj na skyrze z musztardą — zamiast majonezu to ~150 kcal mniej." } },
      ],
    },
  ],
  shopping: [
    { cat: "Warzywa i owoce", icon: "🥬", items: [
      { id: "s1", name: "Ziemniaki", qty: "1,5 kg" },
      { id: "s2", name: "Pomidory i pomidorki cherry", qty: "5 dużych + 2 garście cherry" },
      { id: "s3", name: "Ogórki", qty: "4 sztuki" },
      { id: "s4", name: "Owoce (banany, jabłka, brzoskwinie, borówki, maliny)", qty: "2 banany, 2 jabłka, 2 brzoskwinie, borówki i maliny" },
      { id: "s5", name: "Warzywa (szpinak, rukola, sałata, papryka, rzodkiewka)", qty: "Mieszanka do sałatek, papryka, pęczek rzodkiewki, szczypior" },
      { id: "s6", name: "Fasolka szparagowa (może być mrożona)", qty: "200 g" },
    ]},
    { cat: "Mięso i ryby", icon: "🍖", items: [
      { id: "s7", name: "Pierś z kurczaka", qty: "350 g" },
      { id: "s8", name: "Mięso mielone z indyka", qty: "150 g" },
      { id: "s9", name: "Mięso mielone z chudej wołowiny", qty: "300 g" },
      { id: "s10", name: "Polędwiczka wieprzowa", qty: "400 g" },
      { id: "s11", name: "Łosoś świeży", qty: "150 g" },
      { id: "s12", name: "Łosoś wędzony", qty: "150 g" },
    ]},
    { cat: "Wędliny", icon: "🥓", items: [
      { id: "s13", name: "Szynka z piersi indyka / kurczaka / dojrzewająca", qty: "200 g łącznie" },
    ]},
    { cat: "Nabiał i jaja", icon: "🥚", items: [
      { id: "s14", name: "Jajka rozmiar L", qty: "30 sztuk" },
      { id: "s15", name: "Skyr (naturalny i waniliowy)", qty: "3 opakowania po 150 g" },
      { id: "s16", name: "Puddingi proteinowe", qty: "3 opakowania po 200 g" },
      { id: "s17", name: "Mozzarella light", qty: "1 opakowanie" },
      { id: "s18", name: "Burrata", qty: "1 opakowanie" },
      { id: "s19", name: "Sery w plastrach (cheddar / żółty light)", qty: "1 opakowanie" },
      { id: "s20", name: "Serek wiejski / twaróg chudy / serek kanapkowy", qty: "1 + 1 kostka + 1" },
      { id: "s21", name: "Masło", qty: "1 kostka" },
    ]},
    { cat: "Pieczywo", icon: "🍞", items: [
      { id: "s22", name: "Chleb żytni", qty: "1 duży bochenek" },
      { id: "s23", name: "Tortille pełnoziarniste", qty: "1 opakowanie (4 szt.)" },
      { id: "s24", name: "Bułki pełnoziarniste (do burgerów)", qty: "2 sztuki" },
      { id: "s25", name: "Spód do pinsy", qty: "1 sztuka (duża)" },
    ]},
    { cat: "Produkty suche i inne", icon: "🫙", items: [
      { id: "s26", name: "Makaron pełnoziarnisty / ryż basmati", qty: "100 g + 100 g" },
      { id: "s27", name: "Baton proteinowy", qty: "1 sztuka" },
      { id: "s28", name: "Gorzka czekolada / orzechy włoskie", qty: "1 tabliczka / 1 mała paczka" },
      { id: "s29", name: "Masło orzechowe", qty: "1 słoik (jeśli nie masz)" },
      { id: "s30", name: "Krojone pomidory / passata", qty: "1 puszka / 1 mała passata" },
      { id: "s31", name: "Oliwa z oliwek / miód", qty: "Jeśli nie masz w domu" },
    ]},
  ],
};
